site_name: ELMSLN
pages:
- Home: index.md
- Acronyms: Acronyms.md
- Roadmap: Roadmap.md
- Installation: INSTALL.md
- End User Guide:
  - Adding a course: enduser/add-a-course.md
  - Courses Outline:
    - Editing Content: enduser/courses/edit.md
    - Outline Designer: enduser/courses/outline-designer.md
  - Media asset management:
    - Interactive H5P content: enduser/media/h5p.md
- Information Architecture:
  - Index: ia/ia-index.md
  - System: ia/System.md
  - Roles: ia/User-Roles.md
  - Sections: ia/Sections.md
  - Tools:
    - Service vs. Authority: systems/service-vs-auth.md
    - What is an authority?: systems/authority.md
    - Online: systems/authority/online.md
    - Media: systems/authority/media.md
    - Interact: systems/authority/interact.md
    - People: systems/authority/people.md
    - Inbox: systems/authority/inbox.md
    - LQ: systems/authority/lq.md
    - Grades: systems/authority/grades.md
    - What is a service?: systems/service.md
    - Courses: systems/service/courses.md
    - Studio: systems/service/studio.md
    - Discuss: systems/service/discuss.md
    - Blog: systems/service/blog.md
    - Innovate: systems/developer/innovate.md
- Developer:
  - Structure: development/Package-Structure.md
  - Config Directory: development/config-is-empty-what-do-I-put-there.md
  - Command line: development/command-line.md
  - General Questions: development/Developer-questions.md
  - Concept Development Process: development/Concept-Process.md
  - Release Cycle: development/Project-Release-Cycle.md
  - Scale: development/scale.md
  - Vagrant: development/Vagrant-Step-by-Step-setup.md
  - Should I upgrade modules?: development/Should-I-update-Drupal-modules.md
  - Where can I add modules / themes?: development/Where-can-I-add-new-modules-themes.md
  - Where should I point addresses?: development/Where-should-I-point-addresses.md
  - Features Specification: development/Features-Specification.md
  - Front end:
    - Style Guide: development/front-end/Styleguide.md
    - Front End workflow: development/front-end/Front-End-Development-Workflow.md
  - Upgrades:
    - How do I run upgrades?: development/upgrades/How-do-I-run-upgrades.md
    - MOOC:
      - Optional: development/upgrades/Course-UX-upgrade-for-0.1.0.md
  - Debug : development/debug.md
  - General Infrastructure : development/General-Infrastructure.md
theme: readthedocs
site_author: "elmsln"
repo_name: ELMSLN
repo_url: https://github.com/elmsln/elmsln