# THIS IS NOT YET SUPPORTED
name: elmsln
type: php
docroot: domains
php_version: "7.2"
webserver_type: "apache-fpm"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
  - courses.elmsln
  - media.elmsln
  - online.elmsln
  - analytics.elmsln
  - studio.elmsln
  - interact.elmsln
  - blog.elmsln
  - comply.elmsln
  - discuss.elmsln
  - inbox.elmsln
  - people.elmsln
  - innovate.elmsln
  - grades.elmsln
  - hub.elmsln
  - data-courses.elmsln
  - data-media.elmsln
  - data-online.elmsln
  - data-studio.elmsln
  - data-interact.elmsln
  - data-blog.elmsln
  - data-comply.elmsln
  - data-discuss.elmsln
  - data-inbox.elmsln
  - data-people.elmsln
  - data-innovate.elmsln
  - data-grades.elmsln
  - data-hub.elmsln
  - data-lq.elmsln
provider: default
hooks:
  post-start:
    - exec: "sudo bash /var/www/elmsln/scripts/install/handsfree/ubuntu18/ubuntu18-install.sh elmsln ln elmsln.ddev http admin@elmsln.dev yes"
    - exec: "echo 'finished! go to http://online.elmsln.ddev and login with username admin and password admin.'"